#!/bin/bash
#use it for long running processes to get notified, when they are done like this:
# make; alert make is done
# for gnome use zenity and for pure X use xmessage -nearmouse
kdialog --msgbox "$*"
