#!/bin/bash
 
# command line search script for maven central. Needs curl and xmlstarlet
# installed.

# this looks like it is just solr, so more parameters can be added if needed
NEXUS_URL="http://search.maven.org/solrsearch/select/?wt=xml&rows=20&q="
 
# make sure we got exactly one param
if [ ! $# -eq 1 ]
then
echo "usage $0 <term>"
exit 1
fi
 
curl -s $NEXUS_URL$1 | xmlstarlet sel -T -t -m /response/result/doc \
-v "str[@name='g']" -o " " \
-v "str[@name='a']" -o " " \
-v "str[@name='latestVersion']" -n
