#!/bin/sh
mencoder -forceidx -of lavf -oac mp3lame -lameopts abr:br=56\
         -srate 22050 -ovc lavc \
         -lavcopts vcodec=flv:vbitrate=250:mbd=2:mv0:trell:v4mv:cbp:last_pred=3 \
         -vf scale=360:240 -o $1.flv $1

# stolen from here http://www.jeremychapman.info/cms/mencoder-avi-to-flv-conversion
